In [1]:
import tensorflow as tf

## Find the value of: x^2 + 2*x*y + y^2

### Using Constant

In [2]:
x = tf.constant(1)
y = tf.constant(2)

In [3]:
z = x*x + 2*x*y + y*y

In [4]:
init_op = tf.global_variables_initializer()

In [5]:
sess1 = tf.Session()

In [6]:
sess1.run(init_op)

In [7]:
sess1.run(z)

9

In [8]:
sess1.close()

### Using Variable

In [9]:
x = tf.Variable(1)
y = tf.Variable(2)

In [10]:
z = x*x + 2*x*y + y*y

In [11]:
init_op = tf.global_variables_initializer()

In [12]:
sess2 = tf.Session()

In [13]:
sess2.run(init_op)

In [14]:
sess2.run(z)

9

In [15]:
sess2.close()

### Using Placeholder

In [16]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

In [17]:
z = x*x + 2*x*y + y*y

In [18]:
init_op = tf.global_variables_initializer()

In [19]:
sess3 = tf.Session()

In [20]:
sess3. run(init_op)

In [21]:
sess3.run(z, feed_dict = {x:1, y:2})

9.0

In [22]:
sess3.close()

### Using Placeholder taking input from user

In [23]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

In [24]:
z = x*x + 2*x*y + y*y

In [25]:
init_op = tf.global_variables_initializer()

In [26]:
sess4 = tf.Session()

In [27]:
sess4.run(init_op)

In [28]:
sess4.run(z, feed_dict = {x : input('Enter a value for x: '), y : input('Enter a value for y: ')})

Enter a value for x: 1.0
Enter a value for y: 2.0


9.0

In [29]:
sess4.close()

### Write a program to calculate the distance travelled by an object using the equation of motion:
                                s = u*t+(1/2)*a*t^2
    The object started with initial velocity of 50m/s and is moving with a constant acceleration of 40m/s**2. Time is a variable can be fed at run time by the user.
    t = 3.56 mins.

In [30]:
u = tf.constant(50.0)
a = tf.constant(40.0)
t = tf.placeholder(tf.float32)

In [31]:
s = u * (t*60) + (1/2) * a * (t*60) * (t*60)

In [32]:
init_op = tf.global_variables_initializer()

In [33]:
sess5 = tf.Session()

In [34]:
sess5.run(init_op)

In [35]:
sess5.run(s, feed_dict = {t : input('Enter a value of t: ')})

Enter a value of t: 3.56


923179.2

In [36]:
sess5.close()

### Write a tenserflow program to perform this simple mathematical operation: y = x^2 - 20*x + 100, when x = 5, 10, 20.

In [37]:
x = tf.placeholder(tf.float32)
y = x*x - 20*x + 100
sess6 = tf.Session()
print(sess6.run(y, feed_dict = {x : input('Enter a value for x: ')}))
sess6.close()

Enter a value for x: 5
25.0


In [38]:
x = tf.placeholder(tf.float32)
y = x*x - 20*x + 100
sess7 = tf.Session()
print(sess7.run(y, feed_dict = {x : input('Enter a value for x: ')}))
sess7.close()

Enter a value for x: 10
0.0


In [39]:
x = tf.placeholder(tf.float32)
y = x*x - 20*x + 100
sess8 = tf.Session()
print(sess8.run(y, feed_dict = {x : input('Enter a value for x: ')}))
sess8.close()

Enter a value for x: 20
100.0


### Implement the following in tensorflow:
- X-> variable initialized to 100, Y-> constant to 20, Z-> placeholder, float32, a = X+Y, b = Z*a.
- Print b when z = 25.

In [40]:
X = tf.Variable(100.0)
Y = tf.constant(20.0)
Z = tf.placeholder(tf.float32)

In [41]:
a = X+Y

In [42]:
b = Z*a

In [43]:
init_op = tf.global_variables_initializer()

In [44]:
sess9 = tf.Session()

In [45]:
sess9.run(init_op)

In [46]:
sess9.run(a)

120.0

In [47]:
sess9.run(b, feed_dict = {Z : input('Enter a value for Z: ')})

Enter a value for Z: 25


3000.0

In [48]:
sess9.close()

### Matrix Multiplication

In [49]:
A = tf.Variable([[1,2,3],[4,5,6]])
B = tf.Variable([[7,8],[9,10],[11,12]])

In [50]:
init_op = tf.global_variables_initializer()

In [51]:
sess10 = tf.Session()

In [52]:
sess10.run(init_op)

In [53]:
sess10.run(A)

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
sess10.run(B)

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [55]:
res1 = tf.matmul(A,B)
sess10.run(res1)

array([[ 58,  64],
       [139, 154]])

In [56]:
res2 = tf.matmul(B,A)
sess10.run(res2)

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]])

In [57]:
res3 = tf.multiply(A,10)
sess10.run(res3)

array([[10, 20, 30],
       [40, 50, 60]])

In [58]:
res4 = tf.multiply(B,10)
sess10.run(res4)

array([[ 70,  80],
       [ 90, 100],
       [110, 120]])

### Optimizer

#### Write a tensorflow program to solve: x^2 - 298*x + 22201 = 0.

In [59]:
x = tf.Variable(0.0)

In [60]:
loss = x*x - 298*x + 22201

In [61]:
optimizer = tf.train.GradientDescentOptimizer(0.01) # 0.01 is the learning rate

In [62]:
train = optimizer.minimize(loss)

In [63]:
init_op = tf.global_variables_initializer()
sess11 = tf.Session()
sess11.run(init_op)

In [64]:
sess11.run(x)

0.0

In [65]:
sess11.run(train)

In [66]:
sess11.run(x)

2.98

In [67]:
for i in range(1000):
    sess11.run(train)

In [68]:
sess11.run(x)

148.99963

In [69]:
sess11.close()

### Simple Linear Regression

In [70]:
W = tf.Variable(0.0) # weight
b = tf.Variable(0.0) # bias

In [71]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

In [72]:
linear_model = W*x + b

In [73]:
squared = tf.square(linear_model - y)
loss = tf.reduce_sum(squared)

In [74]:
init_op = tf.global_variables_initializer()
sess12 = tf.Session()
sess12.run(init_op)

In [75]:
sess12.run(loss, feed_dict = {x : [1,2,3,4], y : [0,-1,-2,-3]})

14.0

In [77]:
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

In [78]:
for i in range(1000):
    sess12.run(train, feed_dict = {x : [1,2,3,4], y : [0,-1,-2,-3]})

In [79]:
sess12.run([W,b])

[-0.9999977, 0.9999931]

In [80]:
sess12.close()