In [1]:
# !pip install sklearn

In [2]:
import tensorflow as tf

from sklearn.metrics import accuracy_score

In [3]:
X_input = [[0,0], [0,1], [1,0], [1,1]]
Y_label = [[0], [1], [1], [1]]

In [4]:
# defining the perceptron
# define placeholders for features and labels

x = tf.placeholder(tf.float32, [None,2]) # 2 features
y = tf.placeholder(tf.float32, [None,1]) # labels

In [5]:
# weights and bias

weight = tf.Variable(tf.zeros([2,1]))
bias = tf.Variable(tf.zeros([1]))

# input function
'''mult = tf.matmul(x, weight) # w1*x1 + w2*x2 + ...... + wn*xn
I = tf.add(mult, bias) # w1*x1 + w2*x2 + ...... + wn*xn + wo''' 

I = tf.add(tf.matmul(x, weight), bias)

# activation function
output = tf.sigmoid(I)

print(weight)
print(bias)
print(I)
print(output)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32_ref>
<tf.Variable 'Variable_1:0' shape=(1,) dtype=float32_ref>
Tensor("Add:0", shape=(?, 1), dtype=float32)
Tensor("Sigmoid:0", shape=(?, 1), dtype=float32)


In [6]:
# defining the perceptron ends here
# this section is for training the perceptron

individual_loss = tf.nn.sigmoid_cross_entropy_with_logits(labels = y, logits = output)
loss = tf.reduce_mean(individual_loss)

gdo = tf.train.GradientDescentOptimizer(learning_rate = 0.01)
train = gdo.minimize(loss)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [7]:
# initialize the variables
init = tf.global_variables_initializer()

In [8]:
# create a session
sess = tf.Session()
sess.run(init)

# sess.run(train)

In [9]:
sess.run(weight)

array([[0.],
       [0.]], dtype=float32)

In [10]:
sess.run(bias)

array([0.], dtype=float32)

In [11]:
for i in range(10000):
    sess.run(train, feed_dict = {x: X_input, y: Y_label})

In [12]:
sess.run(weight)

array([[2.0076177],
       [2.0076177]], dtype=float32)

In [13]:
sess.run(bias)

array([-0.46975893], dtype=float32)

In [14]:
result = sess.run(output, feed_dict = {x:X_input})
result

array([[0.38467333],
       [0.82315326],
       [0.82315326],
       [0.9719544 ]], dtype=float32)

In [15]:
ypred = result.round()
ypred

array([[0.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [16]:
accuracy_score(Y_label, ypred)

1.0

### Inference

In [17]:
x1 = [[0,0]]
result = sess.run(output, feed_dict = {x: x1})
result

array([[0.38467333]], dtype=float32)

In [18]:
result.round()

array([[0.]], dtype=float32)

In [19]:
x2 = [[0,1]]
result = sess.run(output, feed_dict = {x: x2})
result

array([[0.8231532]], dtype=float32)

In [20]:
result.round()

array([[1.]], dtype=float32)

In [21]:
x3 = [[1,0]]
result = sess.run(output, feed_dict = {x: x3})
result

array([[0.8231532]], dtype=float32)

In [22]:
result.round()

array([[1.]], dtype=float32)

In [23]:
x4 = [[1,1]]
result = sess.run(output, feed_dict = {x: x4})
result

array([[0.9719544]], dtype=float32)

In [24]:
result.round()

array([[1.]], dtype=float32)