### Dataset Used: iris.csv

In [1]:
import tensorflow as tf

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

from pandas import get_dummies

In [2]:
data=pd.read_csv('C:/Users/Subhadri/Desktop/Data Science - Term 2/Artificial Intelligence/Datasets/iris.csv')
data.head()

petallength  petalwidth  sepallength  sepalwidth  species
0          5.1         3.5          1.4         0.2        0
1          4.9         3.0          1.4         0.2        0
2          4.7         3.2          1.3         0.2        0
3          4.6         3.1          1.5         0.2        0
4          5.0         3.6          1.4         0.2        0

In [3]:
X_input = data.drop(labels = 'species', axis = 1)
Y_label = data['species']

In [4]:
X_input.head()

petallength  petalwidth  sepallength  sepalwidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2

In [5]:
Y_label.head()

0    0
1    0
2    0
3    0
4    0
Name: species, dtype: int64

In [6]:
y_hot = get_dummies(Y_label)
y_hot.head()

0  1  2
0  1  0  0
1  1  0  0
2  1  0  0
3  1  0  0
4  1  0  0

In [7]:
Y_hot_val = y_hot.values
Y_hot_val

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [8]:
#defining the neural network/perceptron
#define place holder for input and label

x = tf.placeholder(tf.float32,[None,4]) #inputs/features - x1,x2,x3,x4
y = tf.placeholder(tf.float32,[None,3]) #labels 

In [9]:
#weights and bias
#no. of neurons are 3 as the no. of classifiers is also 3

weight = tf.Variable(tf.truncated_normal([4,3],stddev = 0.1))
bias = tf.Variable(tf.truncated_normal([3],stddev = 0.1))

#net input function
#multiplied_value=tf.matmul(x,weight)
#I=tf.add(multiplied_value,bias)

netinput = tf.add(tf.matmul(x,weight),bias)

#activation function
output = tf.nn.softmax(netinput) #predicted value

In [10]:
#define the cost/loss function and the optimizer

individual_loss = tf.nn.softmax_cross_entropy_with_logits_v2(labels = y, logits = output)
loss = tf.reduce_mean(individual_loss)

#optimizer
gdo = tf.train.GradientDescentOptimizer(learning_rate = 0.01)
train = gdo.minimize(loss)

In [11]:
#initialize the variables
init = tf.global_variables_initializer()

In [12]:
sess = tf.Session()
sess.run(init)

In [13]:
sess.run(bias)

array([-0.02160304,  0.08059757, -0.1430801 ], dtype=float32)

In [14]:
sess.run(weight)

array([[-0.09719633, -0.09248794, -0.04961695],
       [-0.02103312, -0.12608345,  0.05979464],
       [ 0.0105548 ,  0.05282881,  0.02859129],
       [-0.15183945, -0.04092618, -0.05686674]], dtype=float32)

In [15]:
for i in range(3000):
    final_train = sess.run(train, feed_dict = {x: X_input, y: Y_hot_val})

In [16]:
predict = sess.run(output, feed_dict = {x: X_input})
predict

array([[9.56081569e-01, 4.35322709e-02, 3.86133965e-04],
       [9.15905297e-01, 8.30536559e-02, 1.04110257e-03],
       [9.41412151e-01, 5.78559004e-02, 7.31878972e-04],
       [9.11008298e-01, 8.74111578e-02, 1.58055965e-03],
       [9.60814357e-01, 3.88191268e-02, 3.66524735e-04],
       [9.57169414e-01, 4.23794165e-02, 4.51185653e-04],
       [9.44242835e-01, 5.48496731e-02, 9.07493231e-04],
       [9.41726148e-01, 5.76231778e-02, 6.50686910e-04],
       [8.98636878e-01, 9.93072018e-02, 2.05593184e-03],
       [9.18102026e-01, 8.09208751e-02, 9.77108837e-04],
       [9.62189436e-01, 3.75458077e-02, 2.64769013e-04],
       [9.31027412e-01, 6.79330453e-02, 1.03952433e-03],
       [9.18418825e-01, 8.05983841e-02, 9.82762547e-04],
       [9.42898035e-01, 5.63255288e-02, 7.76427682e-04],
       [9.84330356e-01, 1.56210307e-02, 4.85996934e-05],
       [9.83916342e-01, 1.59966554e-02, 8.70113436e-05],
       [9.76117134e-01, 2.37239823e-02, 1.58917159e-04],
       [9.54068482e-01, 4.54759

In [17]:
result = sess.run(tf.argmax(predict,1)) #taking the highest values position from the 3 classes in row wise order as axis=1
result

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [18]:
confusion_matrix(result,Y_label)

array([[50,  0,  0],
       [ 0, 45,  0],
       [ 0,  5, 50]], dtype=int64)

In [19]:
accuracy_score(result,Y_label) * 100

96.66666666666667