In [1]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

In [2]:
# importing keras libraries

from keras.models import Sequential
from keras.layers import Flatten
from keras.layers import Dense

Using TensorFlow backend.


In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [4]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [5]:
y_train.shape

(60000,)

In [6]:
x_test[10]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  61,   3,
         42, 118, 193, 118, 118,  61,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  14, 179, 245, 236,
        242, 254, 254, 254, 254, 245, 235,  84,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [7]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [8]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [9]:
# instantiating the model
mymodel = Sequential()

In [10]:
# flattening
mymodel.add(Flatten(input_shape = (28,28)))

In [11]:
mymodel.add(Dense(units = 50, activation = 'relu'))
mymodel.add(Dense(units = 350, activation = 'relu'))
mymodel.add(Dense(units = 650, activation = 'relu'))
mymodel.add(Dense(units = 10, activation = 'softmax'))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [12]:
# compiling
mymodel.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [13]:
mymodel.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 50)                39250     
_________________________________________________________________
dense_2 (Dense)              (None, 350)               17850     
_________________________________________________________________
dense_3 (Dense)              (None, 650)               228150    
_________________________________________________________________
dense_4 (Dense)              (None, 10)                6510      
Total params: 291,760
Trainable params: 291,760
Non-trainable params: 0
_________________________________________________________________


In [14]:
mymodel.fit(x_train, y_train, epochs = 10)


Epoch 1/10
60000/60000 [==============================] - 9s 155us/step - loss: 0.2406 - accuracy: 0.9268
Epoch 2/10
60000/60000 [==============================] - 9s 153us/step - loss: 0.1155 - accuracy: 0.9645
Epoch 3/10
60000/60000 [==============================] - 10s 160us/step - loss: 0.0866 - accuracy: 0.9731
Epoch 4/10
60000/60000 [==============================] - 9s 151us/step - loss: 0.0703 - accuracy: 0.9776
Epoch 5/10
60000/60000 [==============================] - 9s 156us/step - loss: 0.0586 - accuracy: 0.9815
Epoch 6/10
60000/60000 [==============================] - 9s 154us/step - loss: 0.0500 - accuracy: 0.9840
Epoch 7/10
60000/60000 [==============================] - 9s 149us/step - loss: 0.0467 - accuracy: 0.9847
Epoch 8/10
60000/60000 [==============================] - 9s 148us/step - loss: 0.0380 - accuracy: 0.9884
Epoch 9/10
60000/60000 [==============================] - 9s 149us/step - loss: 0.0343 - accuracy: 0.9891
Epoch 10/10
60000/60000 [===================

In [15]:
mymodel.evaluate(x_test, y_test)

10000/10000 [==============================] - 1s 56us/step


[0.10751502099884183, 0.9729999899864197]

### Inference
Q. Run inference with test image in location [2516] of the test dataset.

In [16]:
test_image = x_test[2516]
test_image.shape

(28, 28)

In [17]:
test_image = test_image.reshape(1,28,28)

In [18]:
result = mymodel.predict(test_image)
result

array([[2.6670512e-05, 2.8302166e-16, 4.0358080e-07, 2.3134924e-04,
        3.2611513e-09, 4.8940535e-10, 1.7476175e-09, 4.6650106e-12,
        8.2975668e-05, 9.9965858e-01]], dtype=float32)

In [19]:
result.argmax()

9

In [20]:
y_test[2516]

9