In [1]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

In [2]:
# importing keras libraries

from keras.models import Sequential
from keras.layers import Flatten
from keras.layers import Dense

Using TensorFlow backend.


In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [4]:
x_test[10]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  61,   3,
         42, 118, 193, 118, 118,  61,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  14, 179, 245, 236,
        242, 254, 254, 254, 254, 245, 235,  84,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [5]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [6]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [7]:
# instantiating the model
mymodel = Sequential()

In [8]:
# flattening
mymodel.add(Flatten(input_shape = (28,28)))

In [9]:
mymodel.add(Dense(units = 200, activation = 'relu'))
mymodel.add(Dense(units = 100, activation = 'relu'))
mymodel.add(Dense(units = 60, activation = 'relu'))
mymodel.add(Dense(units = 30, activation = 'relu'))
mymodel.add(Dense(units = 10, activation = 'softmax'))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [10]:
# compiling
mymodel.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [11]:
mymodel.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 200)               157000    
_________________________________________________________________
dense_2 (Dense)              (None, 100)               20100     
_________________________________________________________________
dense_3 (Dense)              (None, 60)                6060      
_________________________________________________________________
dense_4 (Dense)              (None, 30)                1830      
_________________________________________________________________
dense_5 (Dense)              (None, 10)                310       
Total params: 185,300
Trainable params: 185,300
Non-trainable params: 0
________________________________________________

In [12]:
mymodel.fit(x_train, y_train, epochs = 10)


Epoch 1/10
60000/60000 [==============================] - 19s 308us/step - loss: 0.2486 - accuracy: 0.9244
Epoch 2/10
60000/60000 [==============================] - 17s 276us/step - loss: 0.1050 - accuracy: 0.9678
Epoch 3/10
60000/60000 [==============================] - 17s 285us/step - loss: 0.0724 - accuracy: 0.9775
Epoch 4/10
60000/60000 [==============================] - 17s 280us/step - loss: 0.0572 - accuracy: 0.9821
Epoch 5/10
60000/60000 [==============================] - 17s 286us/step - loss: 0.0475 - accuracy: 0.9846
Epoch 6/10
60000/60000 [==============================] - 16s 269us/step - loss: 0.0386 - accuracy: 0.9879
Epoch 7/10
60000/60000 [==============================] - 17s 290us/step - loss: 0.0323 - accuracy: 0.9902
Epoch 8/10
60000/60000 [==============================] - 18s 307us/step - loss: 0.0302 - accuracy: 0.9904
Epoch 9/10
60000/60000 [==============================] - 19s 317us/step - loss: 0.0268 - accuracy: 0.9913
Epoch 10/10
60000/60000 [===========

In [13]:
mymodel.evaluate(x_test, y_test)

10000/10000 [==============================] - 2s 194us/step


[0.09574070198359405, 0.9765999913215637]

### Inference

In [14]:
test_image = x_test[25]
test_image.shape

(28, 28)

In [15]:
test_image = test_image.reshape(1,28,28)

In [16]:
result = mymodel.predict(test_image)
result

array([[1.0000000e+00, 1.3974966e-15, 1.0962249e-13, 3.8968743e-14,
        9.7458412e-14, 3.5943589e-15, 3.1440697e-10, 4.8277189e-17,
        7.1416406e-15, 5.2587087e-11]], dtype=float32)

In [17]:
result.argmax()

0

In [18]:
y_test[25]

0