### Create a Multi-layer fully connected neural network with the following configuration of the hidden layers to classify the digits of the MNIST data base. Train and test the model and print the accuracy. Hidden layers configuration:
- Hidden Layer 1 : 300
- Hidden layer 2 : 200
- Hidden layer 3: 100
- Hidden layer 4: 50
- Softmax layer : 10

In [1]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Flatten
from keras.layers import Dense

Using TensorFlow backend.


In [2]:
mnist = tf.keras.datasets.mnist

In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [4]:
x_test[10]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  61,   3,
         42, 118, 193, 118, 118,  61,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  14, 179, 245, 236,
        242, 254, 254, 254, 254, 245, 235,  84,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [5]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [6]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [7]:
# instantiating the model
mymodel = Sequential()

In [8]:
# flattening
mymodel.add(Flatten(input_shape = (28,28)))

In [9]:
mymodel.add(Dense(units = 300, activation = 'relu'))
mymodel.add(Dense(units = 200, activation = 'relu'))
mymodel.add(Dense(units = 100, activation = 'relu'))
mymodel.add(Dense(units = 50, activation = 'relu'))
mymodel.add(Dense(units = 10, activation = 'softmax'))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [10]:
# compiling
mymodel.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [11]:
mymodel.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 300)               235500    
_________________________________________________________________
dense_2 (Dense)              (None, 200)               60200     
_________________________________________________________________
dense_3 (Dense)              (None, 100)               20100     
_________________________________________________________________
dense_4 (Dense)              (None, 50)                5050      
_________________________________________________________________
dense_5 (Dense)              (None, 10)                510       
Total params: 321,360
Trainable params: 321,360
Non-trainable params: 0
________________________________________________

In [12]:
mymodel.fit(x_train, y_train, epochs = 10)


Epoch 1/10
60000/60000 [==============================] - 11s 177us/step - loss: 0.2163 - accuracy: 0.9340
Epoch 2/10
60000/60000 [==============================] - 10s 171us/step - loss: 0.0951 - accuracy: 0.9707
Epoch 3/10
60000/60000 [==============================] - 11s 177us/step - loss: 0.0697 - accuracy: 0.9785
Epoch 4/10
60000/60000 [==============================] - 11s 188us/step - loss: 0.0544 - accuracy: 0.9832
Epoch 5/10
60000/60000 [==============================] - 10s 173us/step - loss: 0.0449 - accuracy: 0.9863
Epoch 6/10
60000/60000 [==============================] - 10s 159us/step - loss: 0.0406 - accuracy: 0.9878
Epoch 7/10
60000/60000 [==============================] - 9s 156us/step - loss: 0.0313 - accuracy: 0.9905
Epoch 8/10
60000/60000 [==============================] - 9s 156us/step - loss: 0.0301 - accuracy: 0.9909
Epoch 9/10
60000/60000 [==============================] - 9s 158us/step - loss: 0.0245 - accuracy: 0.9923
Epoch 10/10
60000/60000 [==============

In [13]:
mymodel.evaluate(x_test, y_test)

10000/10000 [==============================] - 1s 73us/step


[0.08261868761322085, 0.9814000129699707]

### Inference

In [14]:
test_image = x_test[25]
test_image.shape

(28, 28)

In [15]:
test_image = test_image.reshape(1,28,28)

In [16]:
result = mymodel.predict(test_image)
result

array([[1.0000000e+00, 1.4875302e-12, 3.3066319e-12, 3.3782124e-14,
        1.6867118e-16, 4.4615267e-15, 3.7744474e-09, 2.3084009e-16,
        9.5873665e-12, 1.4965439e-11]], dtype=float32)

In [17]:
result.argmax()

0

In [18]:
y_test[31]

1